# Generated by Django 5.1.2 on 2024-12-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='nome',
        ),
    ]
