# Generated by Django 5.1.2 on 2024-12-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_utilizador_apelido_remove_utilizador_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
