# Generated by Django 5.1.2 on 2024-11-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_slug_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
