# Generated by Django 5.1.2 on 2024-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=True),
        ),
    ]
