# Generated by Django 5.1.2 on 2024-12-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
