# Generated by Django 5.1.2 on 2025-01-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
