# Generated by Django 5.1.2 on 2025-01-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomenda',
            options={},
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='cartao',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='morada',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='validade',
        ),
        migrations.RemoveField(
            model_name='itemencomenda',
            name='preco',
        ),
    ]
