# Generated by Django 5.1.2 on 2025-01-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0005_itemencomenda_total_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemencomenda',
            name='total_produto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
