# Generated by Django 5.1.2 on 2025-01-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0006_alter_itemencomenda_total_produto'),
        ('produtos', '0008_alter_produto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='produtos',
            field=models.ManyToManyField(through='encomendas.ItemEncomenda', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=10),
        ),
    ]
