# Generated by Django 5.1.2 on 2025-01-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0007_encomenda_produtos_encomenda_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomenda',
            old_name='status',
            new_name='estado',
        ),
    ]
